import { crmSupabase } from '../config/supabase-multi.js'

// User project service for managing Supabase projects
export const userProjectService = {
  // Create new Supabase project for user
  async createUserProject(userId, projectName) {
    try {
      // Generate unique Supabase project details
      const projectData = {
        user_id: userId,
        project_name: projectName || `${userId}-crm`,
        supabase_url: `https://${userId}-crm.supabase.co`, // This would be generated by Supabase API
        supabase_anon_key: this.generateSupabaseKey(), // This would be generated by Supabase API
        supabase_service_key: this.generateSupabaseKey(true), // This would be generated by Supabase API
        created_at: new Date().toISOString(),
        status: 'active'
      }

      // Store user project in CRM database
      const { data, error } = await crmSupabase
        .from('user_projects')
        .insert([projectData])
        .select()

      if (error) {
        console.error('Error creating user project:', error)
        throw error
      }

      console.log('User project created:', data)
      return data[0]
    } catch (error) {
      console.error('User project creation error:', error)
      throw error
    }
  },

  // Get user's Supabase project details
  async getUserProject(userId) {
    try {
      const { data, error } = await crmSupabase
        .from('user_projects')
        .select('*')
        .eq('user_id', userId)
        .single()

      if (error && error.code !== 'PGRST116') {
        console.error('Error getting user project:', error)
        throw error
      }

      return data
    } catch (error) {
      console.error('Get user project error:', error)
      throw error
    }
  },

  // Update user project details
  async updateUserProject(projectId, updates) {
    try {
      const { data, error } = await crmSupabase
        .from('user_projects')
        .update(updates)
        .eq('id', projectId)
        .select()

      if (error) {
        console.error('Error updating user project:', error)
        throw error
      }

      return data[0]
    } catch (error) {
      console.error('Update user project error:', error)
      throw error
    }
  },

  // Generate mock Supabase key (in real implementation, this would call Supabase API)
  generateSupabaseKey(isServiceKey = false) {
    const prefix = isServiceKey ? 'eyJ' : 'eyJ'
    const mockKey = `${prefix}hbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZXItcHJvamVjdC1pZCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzY3ODMzMjAwLCJleHAiOjIwODM0MDkyMDB9.${Math.random().toString(36).substring(2, 15)}`
    return mockKey
  }
}

export default userProjectService
